services:
  db:
    image: postgres:16-alpine
    container_name: didlydoodash-db
    ports:
      - "4567:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # API service
  api:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: didlydoodash-api
    volumes:
      - .:/app
    ports:
      - "8081:8081" # Map host port 8081 to container port 8081
    env_file:
      - .env
    command: ["air", "-c", ".air.toml"]

volumes:
  postgres_data: